[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@solmate/=lib/solmate/src/",
]

[invariant]
runs = 256
depth = 64
fail_on_revert = true

[lint]
exclude_lints = [
    "mixed-case-variable",
    "screaming-snake-case-immutable"
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
